In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["A", "B", "C", "D"],
    "Marks": [85, 90, 78, 92],
    "Hours": [5, 6, 4, 7]
}

df = pd.DataFrame(data)

df

  Name  Marks  Hours
0    A     85      5
1    B     90      6
2    C     78      4
3    D     92      7

In [3]:
df.head()

  Name  Marks  Hours
0    A     85      5
1    B     90      6
2    C     78      4
3    D     92      7

In [4]:
df.head(2)

  Name  Marks  Hours
0    A     85      5
1    B     90      6

In [5]:
df.tail(3)

  Name  Marks  Hours
1    B     90      6
2    C     78      4
3    D     92      7

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Marks   4 non-null      int64
 2   Hours   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [7]:
df.describe()

           Marks     Hours
count   4.000000  4.000000
mean   86.250000  5.500000
std     6.238322  1.290994
min    78.000000  4.000000
25%    83.250000  4.750000
50%    87.500000  5.500000
75%    90.500000  6.250000
max    92.000000  7.000000

In [8]:
df["Marks"]

0    85
1    90
2    78
3    92
Name: Marks, dtype: int64

In [9]:
df[["Name","Marks"]]

  Name  Marks
0    A     85
1    B     90
2    C     78
3    D     92

In [10]:
df.iloc[0]

Name      A
Marks    85
Hours     5
Name: 0, dtype: object