In [2]:
import pandas as pd
data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Marks": [85, 90, 78, 92, 88],
    "Hours": [5, 6, 4, 7, 6]
}

df = pd.DataFrame(data)

df

  Name  Marks  Hours
0    A     85      5
1    B     90      6
2    C     78      4
3    D     92      7
4    E     88      6

In [3]:
df["Marks"].mean()

np.float64(86.6)

In [4]:
df[df["Marks"] == df["Marks"].max()]

  Name  Marks  Hours
3    D     92      7

In [5]:
df["Performance"] = df["Marks"].apply(lambda x: "Good" if x > 80 else "Average")

df

  Name  Marks  Hours Performance
0    A     85      5        Good
1    B     90      6        Good
2    C     78      4     Average
3    D     92      7        Good
4    E     88      6        Good